### PR TITLE
feat(azure-pg): add restoreDbJob

### PR DESCRIPTION
**Pull request by revolunet**

### CODE REVIEW

**Comment by revolunet** [comment]
Bon il y a un truc bizarre dans les tests e2E : 

```raw
    TSError: ⨯ Unable to compile TypeScript:
    components/hasura.ts(11,3): error TS2322: Type 'import("/Users/xxx/kosko-charts/templates/simple/node_modules/@kosko/env/dist/environment").Environment' is not assignable to type 'import("/Users/xxx/kosko-charts/node_modules/@kosko/env/dist/environment").Environment'.
      Types have separate declarations of a private property 'reducers'.
```

**Comment by douglasduteil** [comment]
@revolunet the dev is connecting to the prod ?

**Comment by revolunet** [comment]
no, the job is executing in the prod cluster and pushing data to a dev database

**Comment by revolunet** [comment]
la suite dans #303

**Pull request closed without merging**
