### PR TITLE
feat(testing): add gitlab.env faker

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by revolunet** [comment]
do we need the .env with RANCHER_PROJECT_ID ?

**Comment by douglasduteil** [comment]
> do we need the .env with RANCHER_PROJECT_ID ?

No one can guest the `RANCHER_PROJECT_ID` so yes.
In practice, one can avoid mentioning it and use the runner env `RANCHER_PROJECT_ID` from a global variable in the Gitlab CI UI... I think 🤔

**Comment by douglasduteil** [comment]
Here, un kosko-chart we need it for testing propose

**Comment by revolunet** [comment]
so we wont need .env in projects for snapshot testing anymore ?

**Comment by douglasduteil** [comment]
hahaha

**Comment by douglasduteil** [comment]
Are we merging this @revolunet ?

**Review by revolunet — APPROVED** [review]

**Pull request merged**
