### PR TITLE
feat: utils. importYamlFolder : load external yamls

### PR DESCRIPTION
**Pull request by revolunet**
Can be used like this in `components/yaml.ts` :

```js
import { importYamlFolder } from "@socialgouv/kosko-charts/utils/importYamlFolder"
import env from "@kosko/env"

const manifests = importYamlFolder(
  path.join(__dirname, "..", `environments/${env.env}/yaml`)
)

export default manifests

### CODE REVIEW

**Comment by douglasduteil** [comment]
@revolunet You may want to add the case you provide as example in the issue description in the kitchen sink e2e test :)

**Comment by douglasduteil** [comment]
Do you need help with the typescript build error ?

**Review by douglasduteil — APPROVED** [review]

**Comment by revolunet** [comment]
i can add the tests, cool if you can help on the TS 😬

**Comment by revolunet** [comment]
kitchen sink ajouté

**Pull request merged**
